// packages/angular/src/index.component.ts
import { Component, Input } from '@angular/core'

import { indexTemplateHtml } from './variables'
// tslint:disable-next-line:no-duplicate-string
import * as common from 'markdown-tip'
export * from 'markdown-tip'

/**
 * @public
 */
@Component({
  selector: 'markdown-tip',
  template: indexTemplateHtml
})
export class MarkdownTipComponent {
  @Input()
  locale?: common.Locale

  get datas() {
    return common.getLocale(this.locale)
  }
  visibleText: string | null = null
  titleClass = common.defaultTitleClass

  mouseenter(data: common.Data, event: MouseEvent) {
    this.visibleText = data.text
    this.titleClass = common.getTitleClass(event.target as HTMLElement)
  }
  mouseleave(data: common.Data) {
    this.visibleText = null
  }
  trackBy(data: common.Data) {
    return data.text
  }
}

// packages/react/src/index.tsx
import * as React from 'react'
// tslint:disable-next-line:no-duplicate-string
import * as common from 'markdown-tip'
export * from 'markdown-tip'

/**
 * @public
 */
export class MarkdownTip extends React.PureComponent<{ locale?: common.Locale | null }, {}> {
  private visibleText: string | null = null
  private titleClass = common.defaultTitleClass

  render() {
    const datas = common.getLocale(this.props.locale)

    const items = datas.map((data, i) => {
      const title = data.text === this.visibleText ? <pre className={this.titleClass}>{data.title}</pre> : null
      return (
        <div className='markdown-tip-item' key={i} onMouseEnter={e => this.mouseenter(data, e)} onMouseLeave={e => this.mouseleave(data)}>
          <span className='markdown-tip-item-text'>{data.text}</span>
          {title}
        </div>
      )
    })

    return (
      <div className='markdown-tip'>
        {items}
      </div>
    )
  }
  private mouseenter(data: common.Data, event: React.MouseEvent<HTMLDivElement>) {
    this.visibleText = data.text
    this.titleClass = common.getTitleClass(event.target as HTMLElement)
    this.setState({ visibleText: this.visibleText, titleClass: this.titleClass })
  }
  private mouseleave(data: common.Data) {
    this.visibleText = null
    this.setState({ visibleText: this.visibleText })
  }
}
